" Vim Configuration

" Determine config directory
let config_dir = expand('<sfile>:p:h')

" Source configuration files
execute 'source ' . config_dir . '/settings.vim'
execute 'source ' . config_dir . '/keymaps.vim'
execute 'source ' . config_dir . '/plugins.vim'
