return {
    'nvim-treesitter/nvim-treesitter',
    branch = 'master',
    lazy = false,
    build = ':TSUpdate',
    config = function()
        require('nvim-treesitter.config').setup({
            ensure_installed = {
                'bash',
                'c',
                'cmake',
                'cpp',
                'css',
                'diff',
                'dockerfile',
                'git_config',
                'git_rebase',
                'gitattributes',
                'gitcommit',
                'glsl',
                'go',
                'html',
                'javascript',
                'json',
                'lua',
                'make',
                'markdown',
                'markdown_inline',
                'meson',
                'python',
                'query',
                'regex',
                'rust',
                'tsx',
                'typescript',
                'vim',
                'vimdoc',
                'yaml',
            },
            highlight = { enable = true },
            indent = { enable = true },
        })
    end,
}
