return {
        'nvim-treesitter/nvim-treesitter',
        branch = 'main',
        lazy = false,
        build = ':TSUpdate',
        config = function()
                local treesitter = require('nvim-treesitter')
                treesitter.install({
                        'agda',
                        'bash',
                        'c',
                        'cmake',
                        'cpp',
                        'css',
                        'csv',
                        'diff',
                        'dockerfile',
                        'ecma',
                        'git_config',
                        'git_rebase',
                        'gitattributes',
                        'gitcommit',
                        'glsl',
                        'go',
                        'html',
                        'html_tags',
                        'javascript',
                        'json',
                        'jsx',
                        'lua',
                        'make',
                        'markdown',
                        'markdown_inline',
                        'meson',
                        'python',
                        'query',
                        'regex',
                        'rust',
                        'tsv',
                        'typespec',
                        'vim',
                        'vimdoc',
                        'yaml',
                })
        end,
}
